@startuml

'End point mappings
class AsylumCaseController {
    - service : AsylumCaseService
    + loadCases() : ResponseEntity<Iterable<AsylumCaseResponseDto>>
    + loadCaseById(asylumCaseRequestDto : AsylumCaseRequestDto) : ResponseEntity<AsylumCaseResponseDto>
}


'Add cache config Annotations in service
interface AsylumCaseService {
    getAllAsylumCases() : ResponseEntity<Iterable<AsylumCaseResponseDto>>
    getAsylumCaseById(asylumCaseRequestDto : AsylumCaseRequestDto) : ResponseEntity<AsylumCaseResponseDto>
}

class AsylumCaseServiceImpl {
    - asylumCaseRepository : AsylumCaseRepository
    - asylumCaseMapper : AsylumCaseMapper
    + getAllAsylumCases() : ResponseEntity<Iterable<AsylumCaseResponseDto>>
    + getAsylumCaseById(asylumCaseRequestDto : AsylumCaseRequestDto) : ResponseEntity<AsylumCaseResponseDto>
}

'Config for DynamoDB
class DynamoDBConfig {
    - awsAccessKey : String
    - awsSecretKey : String
    - awsDynamoDBEndPoint : String
    + amazonAWSCredentials() : AWSCredentials
    + amazonAWSCredentialsProvider() : AWSCredentialsProvider
    + amazonDynamoDB() : AmazonDynamoDB
    + mapper() : DynamoDBMapper
}

'Config to enable caching
class CachingConfig {
    + cacheManager() : CacheManager
}

'repo for DynamoDB calls
interface AsylumCaseRepository <PagingAndSortingRepository<AsylumCase, Integer>>

'Entity for data model
class AsylumCase {
    - id : Integer
    - asylumOffice : String
    - citizenship : String
    - raceOrEthnicity : String
    - caseOutcome : String
    - completion : String
    - currentDate : String
}

class AsylumCaseRequestDto {
    - id : Integer
}

class AsylumCaseResponseDto {
    - asylumOffice : String
    - citizenship : String
    - raceOrEthnicity : String
    - caseOutcome : String
    - completion : String
    - currentDate : String
}

' Part of the  MapStruct dependency
interface AsylumCaseMapper {
    requestToEntity(asylumCaseRequestDto : AsylumCaseRequestDto) : AsylumCase
    entityToResponseDto(asylumCase : AsylumCase) : AsylumCaseResponseDto
    entitiesToResponsesDto(asylumCases : Iterable<AsylumCase>) : Iterable<AsylumCaseResponseDto>
}

'Not owned classes & interfaces
interface PagingAndSortingRepository <CrudRepository> {
    findAll(sort : Sort) : Iterable<AsylumCase>
    findAll(pageable : Pageable) : Page<AsylumCase>
}

interface CrudRepository <Repository> {
    save(asylumCase : AsylumCase) : AsylumCase
    saveAll(iterable : Iterable<AsylumCase>) : Iterable<AsylumCase>
    findById(id : ID) : Optional<AsylumCase>
    existsById(id : ID) : boolean
    findAll() : Iterable<AsylumCase>
    findAllById(ids : Iterable<ID>) : Iterable<AsylumCase>
    count() : long
    deleteById(id : ID) : void
    delete(asylumCase : AsylumCase) : void
    deleteAllById(ids : Iterable<ID>) : void
    deleteAll(asylumCases : Iterable<AsylumCase>) : void
    deleteAll() : void
}

AsylumCaseController *-- AsylumCaseServiceImpl

AsylumCaseServiceImpl <|-- AsylumCaseService
AsylumCaseServiceImpl *-- AsylumCaseRepository
AsylumCaseServiceImpl *-- AsylumCaseMapper
AsylumCaseServiceImpl -- CachingConfig


AsylumCaseMapper .. AsylumCaseRequestDto
AsylumCaseMapper .. AsylumCaseResponseDto

AsylumCaseRequestDto -- AsylumCase

AsylumCaseResponseDto -- AsylumCase

AsylumCaseRepository  o-- PagingAndSortingRepository
AsylumCaseRepository -- DynamoDBConfig

PagingAndSortingRepository  o-- CrudRepository

'Extension/
'Association <|-- (owner <|-- pet) Implements
'Composition *-- (pet *-- leg) Instantiation (part of)
'Aggregation (car o-- wheel) Extends (has a)

@enduml