@startuml
title Miscellaneous Classes
skinparam backgroundcolor lightgrey

'Config for DynamoDB
class DynamoDBConfig {
    - awsAccessKey : String
    - awsSecretKey : String
    - awsDynamoDBEndPoint : String
    + amazonAWSCredentials() : AWSCredentials
    + amazonAWSCredentialsProvider() : AWSCredentialsProvider
    + amazonDynamoDB() : AmazonDynamoDB
    + mapper() : DynamoDBMapper
}

class ErrorDto {
    - message : String
}

class AsylumCaseModel {
    - asylumOffice : String
    - citizenship : String
    - caseOutcome : String
    - completion : String
}
@enduml