@startuml
title Exception Hierarchy
skinparam backgroundcolor lightgrey

class AsylumCaseNotFoundException {
    - {static} final serialVersionUID : long
    - message : String
}

class BadRequestException {
    - {static} final serialVersionUID : long
    - message : String
}

class RuntimeException {}

RuntimeException <|-- BadRequestException
RuntimeException <|-- AsylumCaseNotFoundException
@enduml