@startuml
title Miscellaneous Classes
skinparam backgroundcolor lightgrey

'Config for DynamoDB
class DynamoDBConfig {
    - awsAccessKey : String
    - awsSecretKey : String
    - awsDynamoDBEndPoint : String
    + amazonAWSCredentials() : AWSCredentials
    + amazonAWSCredentialsProvider() : AWSCredentialsProvider
    + amazonDynamoDB() : AmazonDynamoDB
    + mapper() : DynamoDBMapper
}

class ErrorDto {
    - message : String
}

class CasesRequestDto {
    - limit : int
    - page : int
    - citizenship : String
    - outcome : String
    - from : String
    - to : String
    - asylumOffice : String
}

class CaseResponseDto {
    - asylumOffice : String
    - citizenship : String
    - caseOutcome : String
    - completion : String
}
@enduml